[features]
seeds = false
skip-lint = false

[programs.localnet]
infused_carbon_registry = "3g3YSqpjbWGYSSGTEVhP3jLavuLpH3toyE6zgMUrzzoC"

[programs.devnet]
infused_carbon_registry = "3g3YSqpjbWGYSSGTEVhP3jLavuLpH3toyE6zgMUrzzoC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/yann/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]] # sb devnet oracle programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sb devnet oracle IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sb devnet oracle SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb devnet oracle tokenVault
address = "5JYwqvKkqp35w8Nq3ba4z1WYUeJQ1rB36V8XvaGp6zn1"

[[test.validator.clone]] # sb devnet attestation programID
address = "2ie3JZfKcvsRLsJaP5fSo43gUo1vsurnUAtAgUdUAiDG"

[[test.validator.clone]] # sb devnet attestation IDL
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet programState
address = "BzqtGXZPiDSinP4xMFgPf6FLgSa6iPufK4m4JJFgMnTK"

[[test.validator.clone]] # sb SOL feed
address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"

[[test.validator.clone]] # sb mainnet nct usd
address = "4YL36VBtFkD2zfNGWdGFSc5suvskjrHnx3Asuksyek1J"


