[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = "/Users/yann/.config/solana/id.json"

[programs.localnet]
infuzed = "GfnsaGsBQ2bWBdoQ2WsgcwJQAKMUBNJdx9aakWtARMs7"

[programs.devnet]
infuzed = "GfnsaGsBQ2bWBdoQ2WsgcwJQAKMUBNJdx9aakWtARMs7"

[registry]
url = "https://api.apr.dev"

[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=0fe5333d-4590-437f-9a0e-4c3250aff8de"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]]
address = "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J" #BTC_USD Price feed
